Session/6
torakyun/yumemi_training pull request #14
Opened 2022-03-04 08:30 UTC by torakyun

## 概要 

[Session6. VC_LifeCycle](https://github.com/yumemi-inc/ios-training/blob/main/Documentation/VC_Lifecycle.md)

## 修正内容 

- アプリ起動後すぐに天気予報画面にページ遷移
- CLOSEボタンの実装

|after|
|-----|
|![closeButton](https://user-images.githubusercontent.com/67317828/156727475-56f4c755-db6c-46fb-8602-cd5334be9c9a.gif)|

2022-03-05 12:19 UTC, dazy1030 requested changes
すいません遅くなりました！
427b245507dc96b6fd8d9a184c32b9b4a13fcd83　まで確認

2022-03-05 12:19 UTC, dazy1030 commented on YumemiTraining/YumemiTraining/WeatherViewController.storyboard
> +                <viewController modalPresentationStyle="fullScreen" id="AUM-E2-vVA" customClass="WeatherViewController" sceneMemberID="viewController">
@torakyun 
実行してログを眺めていると以下の警告が表示されています
```
YumemiTraining[14634:2621386] [Storyboard] Unknown class WeatherViewController in Interface Builder file.
```

こういった警告は一応動いてはいますがリリースビルド（現在はデバッグビルド）をすると動かなかったりする可能性があります。

結論から言いますと、 WeatherViewController.storyboard のViewControllerのインスペクタ（右側の設定いじるタブ）にある Custom Class の `Inherit Module From Target` にチェックを入れましょう。

原因は WeatherViewController.storyboard のCustom Class の Module が None になっていることが原因です。Moduleとは言い換えるとフレームワークと大体同じ意味で、つまり、指定したカスタムクラスがどのフレームワークのものかを指定する部分になります。 `Inherit Module From Target`（StoryboardファイルのあるModuleと同じ階層にあることにする） のチェックがあり、通常はこちらにチェックが入っているためこのような警告は表示されません。が、今回は一度ファイル名を変更したり認め一時的に WeatherViewController が存在しないクラスとなり、勝手に外れたようですね。

2022-03-07 07:30 UTC, torakyun commented on YumemiTraining/YumemiTraining/ViewController.swift
> +            throw MainError.weatherViewControllerNotFound
https://github.com/torakyun/yumemi_training/pull/14/commits/56775c69d5df76deccb4b5abf4dc0e08d2c76c0a
このコミットで修正しました。

2022-03-07 07:30 UTC, torakyun commented on YumemiTraining/YumemiTraining/ViewController.swift
> +extension ViewController: WeatherViewControllerDelegate {
https://github.com/torakyun/yumemi_training/pull/14/commits/777bf4c72b364e4c439f94b3366cd98f0d5fe063
このコミットで修正しました。

2022-03-07 07:30 UTC, torakyun commented on YumemiTraining/YumemiTraining/WeatherViewController.storyboard
> +                <viewController modalPresentationStyle="fullScreen" id="AUM-E2-vVA" customClass="WeatherViewController" sceneMemberID="viewController">
https://github.com/torakyun/yumemi_training/pull/14/commits/58e8a6f92e2c56526da64fbfa5790a93634b07c1
このコミットで修正しました。

2022-03-07 07:31 UTC, torakyun commented
レビューありがとうございます！

2022-03-07 13:01 UTC, dazy1030 commented on YumemiTraining/YumemiTraining/ViewController.swift
> +            throw MainError.weatherViewControllerNotFound
@torakyun 
未使用のエラーは削除してください

2022-03-07 13:02 UTC, dazy1030 requested changes
58e8a6f92e2c56526da64fbfa5790a93634b07c1 まで確認

2022-03-08 01:11 UTC, torakyun commented on YumemiTraining/YumemiTraining/ViewController.swift
> +            throw MainError.weatherViewControllerNotFound
https://github.com/torakyun/yumemi_training/pull/14/commits/aeeafcd6a8a38a28ca83b9d6255a902a23522129
このコミットで修正しました。

2022-03-08 12:40 UTC, dazy1030 approved these changes
aeeafcd6a8a38a28ca83b9d6255a902a23522129 まで確認

2022-03-08 12:45 UTC, dazy1030 commented
@torakyun 
PRを作成するときは、そのブランチを切った元のブランチに向けるようにしましょう。
例えば、次のsession7のPRであれば（おそらく）このブランチから切っているはずなので、
`main ← session/7` とするのではなく、 `session/6 ← session/7` としましょう。
こうしておくと、そのブランチで発生した差分のみが表示されます。（今セッション7のPRでは7と6の差分がまとめて表示されてしまっています。）
また、session/6がマージされると、自動的に `main ← session/7` となります。

2022-03-08 12:54 UTC, torakyun commented
マージ先を変更しておきました。

2022-03-08 12:54 UTC, merged