APIを非同期に処理
torakyun/yumemi_training pull request #17
Opened 2022-03-08 04:13 UTC by torakyun

## 概要 

[Session9. スレッドブロック](https://github.com/yumemi-inc/ios-training/blob/main/Documentation/ThreadBlock.md)

## 修正内容 

- 呼び出しAPIを`Sync ver`に変更する
- 非同期にAPIを呼び出す
- APIの処理が戻るまでUIActivityIndicatorを表示する
- Result型を用いてAPIの戻り値をハンドリング

|after| 
|-----| 
|![a](https://user-images.githubusercontent.com/67317828/157164424-cade9abd-8be0-43ae-879c-1de438aa438d.gif)|

2022-03-08 13:27 UTC, dazy1030 requested changes
a42472db052205c31738f6e365e0a163b2d23b9a まで確認

2022-03-08 13:27 UTC, dazy1030 commented on YumemiTraining/YumemiTraining/WeatherViewController.swift
> +        let weatherPrameter = WeatherParameter(area: "tokyo", date: "2020-04-01T12:00:00+09:00")
@torakyun 
前回見逃していましたが、誤字してますね。 parameter

2022-03-08 13:27 UTC, dazy1030 commented on YumemiTraining/YumemiTraining/WeatherViewController.swift
> +        }
@torakyun 
ここでは `capture list` を使用する必要があります。（[weak self] みたいな書き方のこと）
```swift
let weatherResult = Result { try WeatherAPI.fetchWeather(weatherPrameter)}
```
で2秒間処理が止まります。この間にCloseボタンを押すとどうなるでしょう。
閉じるときにWeatherViewControllerを破棄しようとしますが、
WeatherViewControllerつまりselfは `DispatchQueue.main.async { ... }` のクロージャの中に記述されており強参照でキャプチャされているため破棄することができません。以下のようにキャプチャリストで弱参照にすることで、キャプチャすることを回避できます。
```swift
DispatchQueue.main.async { [weak self] in
    ...
}
```
またこれだけでは足りません。
`DispatchQueue.main.async { [weak self] in` のリストに書かれたselfもまた、 `DispatchQueue.global().async` で強参照されているためです。同様に弱参照にしてください。

キャプチャリストで弱参照としたとき、そのプロパティはOptionalとなりますが、nilとなっているときつまりWeatherViewControllerが破棄されていたときは何もしなくて良いため、 `guard let` 文で何もせずに抜けてしまいましょう。
```swift
guard let self = self else { return }
```

2022-03-08 13:27 UTC, dazy1030 commented on YumemiTraining/YumemiTraining/WeatherViewController.swift
> +            let weatherResult = Result { try WeatherAPI.fetchWeather(weatherPrameter)}
@torakyun 
`{ ... }` で囲うときは、内側にスペースを開けるようにしましょう。
```suggestion
            let weatherResult = Result { try WeatherAPI.fetchWeather(weatherPrameter) }
```

2022-03-09 03:26 UTC, torakyun commented on YumemiTraining/YumemiTraining/WeatherViewController.swift
> +        }
https://github.com/torakyun/yumemi_training/pull/17/commits/5e78a6917d6ccd5f2c94d8a11bc55b55b6ff8ddf
このコミットで修正しました。

2022-03-09 03:28 UTC, torakyun commented on YumemiTraining/YumemiTraining/WeatherViewController.swift
> +        let weatherPrameter = WeatherParameter(area: "tokyo", date: "2020-04-01T12:00:00+09:00")
https://github.com/torakyun/yumemi_training/pull/17/commits/2e56579640b2a0d9c5533c4fa44ef764a3c3bda7
このコミットで修正しました。

2022-03-09 03:29 UTC, torakyun commented on YumemiTraining/YumemiTraining/WeatherViewController.swift
> +            let weatherResult = Result { try WeatherAPI.fetchWeather(weatherPrameter)}
https://github.com/torakyun/yumemi_training/pull/17/commits/ad5b5d29d0c1262092d719a767d85c558d7645b1
このコミットで修正しました。

2022-03-09 06:35 UTC, dazy1030 approved these changes
5e78a6917d6ccd5f2c94d8a11bc55b55b6ff8ddf　まで確認

2022-03-09 06:42 UTC, merged