AutoLayoutで画面のレイアウトを構成
torakyun/yumemi_training pull request #2
Opened 2022-02-22 02:30 UTC by torakyun

## 概要 

[Session1. AutoLayout](https://github.com/yumemi-inc/ios-training/blob/main/Documentation/AutoLayout.md)

## 修正内容 

- AutoLayoutを用いて、天気予報アプリの画面レイアウトを構成する

|goal|work| 
|-----|-----| 
|![image](https://user-images.githubusercontent.com/67317828/155047930-384f0db4-1ef1-4f41-ab54-ebfe7ae97fcd.png)|<img width="285" alt="スクリーンショット 2022-02-22 11 13 23" src="https://user-images.githubusercontent.com/67317828/155050568-e94d35c9-f60a-40b3-8ee0-dea125ec8ef2.png">| 

## その他

- 指定条件以外にも、Goalの見た目に近づくように「フォントサイズ」や「ラベルの高さ」を指定した

2022-02-22 03:12 UTC, dazy1030 commented
@torakyun 
自分の担当するissueと、担当したpull request（PR）には自分自身をアサインしましょう。
issue, PRを作る最中、または作った後のページでの右側の `assign yourself` を押してみてください。

2022-02-22 03:23 UTC, dazy1030 commented on YumemiTraining/YumemiTraining/Base.lproj/Main.storyboard
> +                                            <constraint firstItem="Bo2-9X-vtS" firstAttribute="width" secondItem="DS6-Iu-KSd" secondAttribute="width" multiplier="0.5" id="4hk-gD-k9y"/>
@torakyun 
UIStackViewは、中に入れたViewのサイズをどうするか決定する `Distribution` プロパティがあります。
https://developer.apple.com/documentation/uikit/uistackview/distribution

これの `fillEqually` を使うことで、それぞれのラベルに、スタックビューの半分の幅という制約はつけなくて良くなります。

2022-02-22 03:42 UTC, dazy1030 commented on YumemiTraining/YumemiTraining/CustomLabel.swift
> +class CustomLabel: UILabel {
@torakyun 
使用しないクラス・ファイルはコミットに含めないようにするのが良いです。
将来的に使用するものでも、このコミットと関係ない場合は含めない方が、レビュワー（レビューする人）が読みやすくなります。

このファイルは削除するようお願いします。

2022-02-22 04:04 UTC, dazy1030 commented on YumemiTraining/YumemiTraining/Base.lproj/Main.storyboard
> +<document type="com.apple.InterfaceBuilder3.CocoaTouch.Storyboard.XIB" version="3.0" toolsVersion="19529" targetRuntime="iOS.CocoaTouch" propertyAccessControl="none" useAutolayout="YES" useTraitColle
@torakyun 
今回の[課題](https://github.com/yumemi-inc/ios-training/blob/main/Documentation/AutoLayout.md)を見る限り、レイアウトの指定はありますが特に色やフォントの指定はないので頑張らなくても大丈夫です（はっきりいって課題の指定が曖昧すぎる）。また、画面が回転した場合のことも述べられていないので気にしなくて良いです。

課題のページのレイアウトを忠実に行いましょう。
1. Viewに縦向きのStackView（MainStackViewと呼称）を配置
2. MainStackViewの幅をViewの半分になるよう制約をかける（ここで注意はSafeAreaではなくViewに対してかけること）
3. MainStackViewの位置をViewの中央になるよう制約をかける（こちらもViewに対してかけるよう注意）
2. MainStackViewにImageViewと横向きのStackView（LabelStackViewと呼称）を配置
3. LabelStackViewにLabelを2つ配置
4. LabelStackViewのDistributionを `Fill Equally` に設定（これでStackView内部のViewの幅が全て同じになる）
5. ImageViewのAspect Ratioを1:1になるよう制約をかける（これで正方形になる）
6. MainStackViewの下に新たに横向きのStackView（ButtonStackViewと呼称）を配置
7. ButtonStackViewのX方向の中央の位置をMainStackViewと同じになるよう制約をかける
8. ButtonStackViewのTopをMainStackViewのBottomから80pt下になるよう制約をかける
9. ButtonStackViewの幅がMainStackViewと同じになるよう制約をかける
9. ButtonStackViewにButtonを2つ配置
10. 終了！

2022-02-22 04:09 UTC, dazy1030 commented on YumemiTraining/YumemiTraining/ViewController.swift
> +
@torakyun 
こちらも、差分が出ていますがこのPRとは関係ないので本来は出さないようにお願いします。
考え方としては、PRの目的以外の変更は加えない、ですね。

2022-02-22 04:10 UTC, dazy1030 requested changes
https://github.com/torakyun/yumemi_training/pull/2/commits/bbd4314cb013ee4d342f42990ee10ec8d16fd903 まで確認

2022-03-01 02:11 UTC, torakyun commented on YumemiTraining/YumemiTraining/Base.lproj/Main.storyboard
> +                                            <constraint firstItem="Bo2-9X-vtS" firstAttribute="width" secondItem="DS6-Iu-KSd" secondAttribute="width" multiplier="0.5" id="4hk-gD-k9y"/>
2個下のコメントで修正したことを記載しました。

2022-03-01 02:11 UTC, torakyun commented on YumemiTraining/YumemiTraining/CustomLabel.swift
> +class CustomLabel: UILabel {
https://github.com/torakyun/yumemi_training/pull/2/commits/beea452fc366f1655f02a2356c150841775d7340
このコミットで修正しました。

2022-03-01 02:11 UTC, torakyun commented on YumemiTraining/YumemiTraining/ViewController.swift
> +
https://github.com/torakyun/yumemi_training/pull/2/commits/eb94b6e81e28977a88f1df2dc8340cabefcb8cd3
このコミットで修正しました。

2022-03-01 02:50 UTC, dazy1030 commented on YumemiTraining/YumemiTraining/Base.lproj/Main.storyboard
> +<document type="com.apple.InterfaceBuilder3.CocoaTouch.Storyboard.XIB" version="3.0" toolsVersion="19529" targetRuntime="iOS.CocoaTouch" propertyAccessControl="none" useAutolayout="YES" useTraitColle
@torakyun 
いくつか修正をお願いします。
* 画像（画像を含むStackView）の幅が画面の半分という課題が満たせていません
* 画像の下にあるラベルを覆うStackViewに、画像の高さの0.2倍という制約がありますが課題には含まれないので削除お願いします
* 画像の下にあるラベルを覆うStackViewの横幅を指定していますが、StackViewに含まれるViewはデフォルトで広がるという制約を持つので指定する必要はありません。削除お願いします

2022-03-01 02:58 UTC, torakyun commented on YumemiTraining/YumemiTraining/Base.lproj/Main.storyboard
> +<document type="com.apple.InterfaceBuilder3.CocoaTouch.Storyboard.XIB" version="3.0" toolsVersion="19529" targetRuntime="iOS.CocoaTouch" propertyAccessControl="none" useAutolayout="YES" useTraitColle
https://github.com/torakyun/yumemi_training/pull/2/commits/d71589c00f100a839707b890e7579aa3c6bfbd5d
このコミットで修正しました。ついでに、各スタックビューに名前をつけました。

2022-03-01 13:14 UTC, dazy1030 approved these changes
https://github.com/torakyun/yumemi_training/pull/2/commits/d71589c00f100a839707b890e7579aa3c6bfbd5d まで確認。LGTM!

2022-03-01 13:28 UTC, dazy1030 commented
@torakyun 
この後の流れです。

## PRをマージする
* 規定の人数のレビュワーがApproveしたらプルリクエスト（PR）をマージしましょう。
* この課題では常にぼく1人がレビュワーなのでぼくがApproveしたらマージして問題ありません。
    ![image](https://user-images.githubusercontent.com/21330273/156176118-e463d955-472a-4c2a-9350-b55f557df25e.jpg)
* このボタンを押してマージまですると、このPRが緑色から紫色に変わります。

## 作業ブランチを削除する
* PRをマージしたらPRの作業ブランチは不要になりますので削除しましょう。
* 削除と言いつつ、一度リモートにPushしたブランチは削除してもいつでも戻すことができるので心配はいりません。
* PRマージされ紫色に変わったあと、Delete branch みたいなボタンが出現するので、そちらを押して削除してください。

## 他の作業ブランチにマージする
* PRがマージされるとリモートのmainブランチPRの内容分進むので、まずはローカルにPullしましょう。
* mainをPullした後、他の作業ブランチ（例えば session/2 など）にmainを（ローカルで）マージしてこのPRの作業内容を他の作業ブランチに反映させます。
* 個人的にRebaseはあまりお勧めしません。が、このあたりの判断は一緒に開発するチームに合わせるのが無難です。

2022-03-02 01:04 UTC, merged