delegateを用いてAPIでの処理を委譲
torakyun/yumemi_training pull request #20
Opened 2022-03-08 09:57 UTC by torakyun

## 概要 

[Session10. Delegateパターン](https://github.com/yumemi-inc/ios-training/blob/main/Documentation/Delegate.md)

## 修正内容 

- Delegateパターンを使い、APIから天気予報を受け取る
- ViewControllerに`deinit`を実装し、ログを出力するようにしておく
- ViewControllerを閉じた時に`deinit`が呼ばれることを確認する

2022-03-08 10:12 UTC, torakyun commented
https://github.com/torakyun/yumemi_training/pull/20/commits/0a3ca07d777d4b99b07808aa0194efbe68c7a29b
このコミットでdelegateを実装しました。
ボタンが押された処理とAPIの処理の２つを、delegateで別々のクラスに委譲しています。名前をdelegateとdelegate2としていますが、良い方法はありますか。

2022-03-08 14:56 UTC, dazy1030 requested changes
コメントにも書きましたが、今回は端的に答えを書いていない部分が多いです。たくさん質問してもらって構いませんので頑張ってみてください！

38c82d419074a164210c002c9140b1cbfa108369 まで確認

2022-03-08 14:56 UTC, dazy1030 commented on YumemiTraining/YumemiTraining/APIs/WeatherModelImpl.swift
> +extension WeatherModelImpl: WeatherViewControllerDelegate2 {
@torakyun 
間違って覚えちゃってますね。まずはprotocolがなんなのかを理解した上でDelegateとして使えるようになりましょう。

この使い方は依存度を下げるときに使用される `抽象化` です。依存度が高いとは以下のようなときです。
```swift
class SampleClass {
    let api = WeatherAPIImpl()
}
```
このとき、SampleClassで天気を取得するクラスはWeatherAPIImplというクラスでなければなく他のものでは成り立ちません。依存度が高いとき、一般的に変更に弱い実装となっています。

天気を取得するAPIはほかのものでも良いはずです。つまり、areaとdateを渡したらWeatherResultを返してくれる `何か` ならなんでも良いわけです。Swiftではその何か特定のクラスではないけどこういった実装がされている（抽象的な）ものを `protocol` で表現できます。protocolの基本的な使い方です。今回でいえばこうです。
```swift
protocol WeatherAPI {
    func fetchWeather(at area: String, date: Date) throws -> WeatherResult
}
```

protocolは当然、何かこんなもの、といった概念なので、使用するときにはそのprotocolに準拠した実態を与える必要があります。（ちなみに `impl` とは `implementation` のことで抽象との対義である `具象` や `実装` といった意味です）
```swift
class WeatherAPIImpl: WeatherAPI {
    func fetchWeather(at area: String, date: Date) throws -> WeatherResult {
        ...
    } 
}

class SampleClass {
    let api: WeatherAPI = WeatherAPIImpl()
}
```

このままだとなんの意味もないですが、このWeatherAPIが外から与えられるときはどうでしょうか。
```swift
class SampleClass {
    let api: WeatherAPI

    init(api: WeatherAPI) {
        self.api = api
    }
}

class UserClass {
    let sample = SampleClass(api: WeatherAPIImpl())
}
```
SampleClassからWeatherAPIImplの記述が消え、依存度が低くなりました。依存するクラスが別のフレームワークであったり、他のチームの人が開発している場合などに、依存度が低いと別のフレームワークへの乗り換え（変更）に強くなります

2022-03-08 14:56 UTC, dazy1030 commented on YumemiTraining/YumemiTraining/APIs/WeatherModelImpl.swift
> +    private lazy var dateFormatter: DateFormatter = {
@torakyun 
lazy varは以下の性質があります。
* lazy var で定義した変数は、その変数が使用されるときになって初めてインスタンス化される（遅延評価）
    * 今回でいえば、fetchWeatherが呼ばれるまではインスタンスが生成されない
* 遅延評価される性質上、selfを使用することができる
    ```swift
    class Sample {
        let value = 10
        let value2 = self.value + 20 // これはできない
        lazy var value3 = self.value + 30 //これはできる
    }
    ```
* 必ず `var` にしなければならない

遅延評価は無駄なインスタンスの生成を行わないため、パフォーマンスは多少良くなりますが、var で宣言しないといけない弱点があります。相当大きなインスタンスでない限りはlazy var は使用しないことをお勧めします。

2022-03-08 14:56 UTC, dazy1030 commented on YumemiTraining/YumemiTraining/WeatherViewController.swift
> +    var delegate2: WeatherViewControllerDelegate2?
@torakyun 
上記の抽象化としてのprotocolの使用法を理解した上で読んでみてください。

Delegateとは、 `処理の続きを行なってくれる（移譲できる）なにかしら` をprotocolを使って表しているといえます。
例えば、 
```swift
protocol WeatherViewControllerDelegate: AnyObject {
    func weatherViewControllerDidPressClose(_ viewController: WeatherViewController)
}
```
WeatherViewControllerDelegateは、Closeボタンを押したときの続きの処理を実装した何かしら、という `抽象的` な表現をprotocolで表しています。そして
```swift
extension ViewController: WeatherViewControllerDelegate {
    func weatherViewControllerDidPressClose(_ viewController: WeatherViewController) {
        ...
    }
}
```
ViewControllerは実際に `weatherViewControllerDidPressClose` を実装している `具体的` なクラスといえます。（処理の続きをここに書く）


これらを踏まえた上で、今回実装すべきprotocolは `APIの実行が終わった後の処理を実装した何か` です。そして処理を委譲するのはAPI側からです。

今回はあえて答えを書かないようにします。試行錯誤と質問を繰り返して答えに辿り着きましょう！

2022-03-09 05:51 UTC, torakyun commented on YumemiTraining/YumemiTraining/APIs/WeatherModelImpl.swift
> +    private lazy var dateFormatter: DateFormatter = {
https://github.com/torakyun/yumemi_training/pull/20/commits/d3a0689d6c822dbb9136ea12d199d05297bd7362
このコミットで修正しました。

2022-03-09 05:51 UTC, torakyun commented on YumemiTraining/YumemiTraining/WeatherViewController.swift
> +    var delegate2: WeatherViewControllerDelegate2?
https://github.com/torakyun/yumemi_training/pull/20/commits/af4ec45209b65c2f1e4baf9b3f32ddda0d16a552
このコミットで修正しました。

2022-03-09 05:52 UTC, torakyun commented on YumemiTraining/YumemiTraining/APIs/WeatherModelImpl.swift
> +extension WeatherModelImpl: WeatherViewControllerDelegate2 {
下記のコメントで修正しました。

2022-03-09 06:41 UTC, dazy1030 commented on YumemiTraining/YumemiTraining/WeatherViewController.swift
> +    func handleWeather(_ result: Result<WeatherResult, Error>)
@torakyun 
Delegateメソッドの書き方は決まりがあります。ViewController系のDelegateを参考に書き直してみてください。

2022-03-09 06:41 UTC, dazy1030 commented on YumemiTraining/YumemiTraining/WeatherViewController.swift
> +protocol WeatherModelDelegate: AnyObject {
@torakyun 
DelegateはModelImplの方に移してください

2022-03-09 06:43 UTC, dazy1030 commented on YumemiTraining/YumemiTraining/WeatherViewController.swift
> +    var weatherModel: WeatherModel?
@torakyun 
外から参照する必要はないように見えます。またvarである必要もなさそうです。

2022-03-09 06:43 UTC, dazy1030 commented on YumemiTraining/YumemiTraining/WeatherViewController.swift
> +    }
@torakyun 
コンストラクタ系はUIViewControllerのメソッドよりも上に書いておきましょう

2022-03-09 06:45 UTC, dazy1030 commented on YumemiTraining/YumemiTraining/WeatherViewController.swift
> +protocol WeatherModel {
@torakyun
WeatherModelは別ファイルにしましょう。Delegateに関しては別ファイルというのはあまり見かけませんね🤔

2022-03-09 06:46 UTC, dazy1030 commented on YumemiTraining/YumemiTraining/APIs/WeatherModelImpl.swift
> +//
@torakyun 
session9をこのブランチに取り込んでください。コンフリクトしています。

2022-03-09 06:46 UTC, dazy1030 requested changes
af4ec45209b65c2f1e4baf9b3f32ddda0d16a552 まで確認

2022-03-09 08:17 UTC, torakyun commented on YumemiTraining/YumemiTraining/WeatherViewController.swift
> +    }
https://github.com/torakyun/yumemi_training/pull/20/commits/18f136c8d301265c239c3e038f6f362b350d8007
このコミットで修正しました。

2022-03-09 08:18 UTC, torakyun commented on YumemiTraining/YumemiTraining/WeatherViewController.swift
> +    var weatherModel: WeatherModel?
https://github.com/torakyun/yumemi_training/pull/20/commits/c63ba234102577df868ace8ebd9e260a39733d2b
このコミットで修正しました。

2022-03-09 08:18 UTC, torakyun commented on YumemiTraining/YumemiTraining/WeatherViewController.swift
> +protocol WeatherModel {
https://github.com/torakyun/yumemi_training/pull/20/commits/4f62ccf97935cb7d453cde70ddeefa80e0176369
このコミットで修正しました。

2022-03-09 08:19 UTC, torakyun commented on YumemiTraining/YumemiTraining/WeatherViewController.swift
> +protocol WeatherModelDelegate: AnyObject {
https://github.com/torakyun/yumemi_training/pull/20/commits/9d451e727fd32f2e0aaf7211fb5b0fb8f78be5e7
このコミットで修正しました。

2022-03-09 08:19 UTC, torakyun commented on YumemiTraining/YumemiTraining/WeatherViewController.swift
> +    func handleWeather(_ result: Result<WeatherResult, Error>)
https://github.com/torakyun/yumemi_training/pull/20/commits/cb1e27b38fd5e65c5f962166cff30cac23ff183f
このコミットで修正しました。

2022-03-09 08:20 UTC, torakyun commented on YumemiTraining/YumemiTraining/APIs/WeatherModelImpl.swift
> +//
https://github.com/torakyun/yumemi_training/pull/20/commits/a988af42887ccb6b974bab92c4dcdb3f9e8b5799
このコミットで修正しました。

2022-03-09 08:27 UTC, dazy1030 commented on YumemiTraining/YumemiTraining/WeatherViewController.swift
> +extension WeatherViewController: WeatherModelDelegate {
@torakyun 
MARKコメントを書きましょう

2022-03-09 08:35 UTC, dazy1030 commented on YumemiTraining/YumemiTraining/APIs/WeatherModelImpl.swift
> +    func weatherModelDidFetchWeather(_ weatherModelImpl: WeatherModelImpl, _ result: Result<WeatherResult, Error>)
@torakyun 
delegateメソッドの命名は今は2パターンだけ覚えておけばOKです

### 引数を必要としない時
* メソッド名が `委譲元のクラス名` + `何が起こったか`
* 引数が `(_ 委譲元のクラス名の一般名: 委譲元のクラス)`
```swift
func weatherModelDidCancelFetchWeather(_ weatherModel: WeatherModel)
```

### 引数が必要な時
* メソッド名は `委譲元のクラス名` のみ
* 引数が `(_ 委譲元のクラス名の一般名: 委譲元のクラス, 何が起こって 何を渡すか: 渡すクラス)`
```swift
func weatherModel(_ weatherModel: WeatherModel, didFailWithError error: Error)
```

2022-03-09 08:38 UTC, dazy1030 commented on YumemiTraining/YumemiTraining/APIs/WeatherModelImpl.swift
> +    func weatherModelDidFetchWeather(_ weatherModelImpl: WeatherModelImpl, _ result: Result<WeatherResult, Error>)
@torakyun 
このDelegateがImplのものの固有のDelegateであればすべて Impl つけてください。
固有のものでなければ、すべて Impl を外してください

2022-03-09 08:39 UTC, dazy1030 commented on YumemiTraining/YumemiTraining/WeatherViewController.swift
> +        weatherModel.fetchWeather(at: "tokyo", date: Date())
@torakyun 
self お願いします

2022-03-09 08:41 UTC, dazy1030 commented on YumemiTraining/YumemiTraining/WeatherViewController.swift
> +            case .success(let data):
@torakyun 
列挙で引数を持つ場合は以下のように書くようお願いします。
```swift
case let .success(data):
    ...
```
どちらでも問題はありませんが、ミクチャでの決まり事のようなものです。

2022-03-09 08:42 UTC, dazy1030 requested changes
a988af42887ccb6b974bab92c4dcdb3f9e8b5799 まで確認

2022-03-09 09:00 UTC, torakyun commented on YumemiTraining/YumemiTraining/WeatherViewController.swift
> +        weatherModel.fetchWeather(at: "tokyo", date: Date())
https://github.com/torakyun/yumemi_training/pull/20/commits/46f57ca15c3b832152d2b2568ac2ad3cd4a1c9f3
このコミットで修正しました。

2022-03-09 09:02 UTC, torakyun commented on YumemiTraining/YumemiTraining/APIs/WeatherModelImpl.swift
> +    func weatherModelDidFetchWeather(_ weatherModelImpl: WeatherModelImpl, _ result: Result<WeatherResult, Error>)
https://github.com/torakyun/yumemi_training/pull/20/commits/3f193eba57507bfff14170fbf6428e02a493fe80
このコミットで修正しました。

2022-03-09 09:05 UTC, torakyun commented on YumemiTraining/YumemiTraining/WeatherViewController.swift
> +extension WeatherViewController: WeatherModelDelegate {
https://github.com/torakyun/yumemi_training/pull/20/commits/4f717a8fbefb21fdf459106fbfc1f5e145240e21
このコミットで修正しました。

2022-03-09 09:11 UTC, dazy1030 commented on YumemiTraining/YumemiTraining/WeatherViewController.swift
> +extension WeatherViewController: WeatherModelDelegate {
@torakyun 
細かいですが、MARKの前後には1行ずつ空けてください

2022-03-09 09:14 UTC, torakyun commented on YumemiTraining/YumemiTraining/WeatherViewController.swift
> +extension WeatherViewController: WeatherModelDelegate {
このコミットで修正しました。

2022-03-09 09:24 UTC, dazy1030 approved these changes
cad0d0a7fdc7194b99a55cd498246bbbe6bcc894 までLGTM！
Delegateやprotocolは難しい概念ですが、マスターできれば中〜上級者くらいかなと思っています。（特にprotocolはさらに応用がたくさんあります）
繰り返しで頑張って覚えましょう！

2022-03-09 09:25 UTC, merged