viewControllerのメソッドをReactiveSwiftで実装
torakyun/yumemi_training pull request #29
Opened 2022-03-11 10:30 UTC by torakyun

## 概要

viewControllerのメソッドをReactiveSwiftで実装

## 修正内容

-  瞬時に終わる天気取得APIに変更
-  foregroundに戻った時の処理をReactiveSwiftに変更
-  viewDidAppearをReactiveSwiftに変更

2022-03-12 05:08 UTC, dazy1030 commented on YumemiTraining/YumemiTraining/ReactiveWeatherViewController.swift
@torakyun 
UIの変数にprivateつけてください。今回の修正分ではないけど、前のPRをレビューしてなかったので

2022-03-12 05:13 UTC, dazy1030 requested changes
5389963c33560537d7b733bf59eb21c490cd2de2 まで確認しました

2022-03-13 02:39 UTC, torakyun commented on YumemiTraining/YumemiTraining/ReactiveWeatherViewController.swift
https://github.com/torakyun/yumemi_training/pull/29/commits/5656b82167b84ba55f487a79f6d7cfbf61ed194d
このコミットで修正しました。

2022-03-13 12:38 UTC, dazy1030 approved these changes
5656b82167b84ba55f487a79f6d7cfbf61ed194d まで確認

2022-03-15 01:10 UTC, merged