APIをSignalProducerに変更
torakyun/yumemi_training pull request #31
Opened 2022-03-15 03:35 UTC by torakyun

## 概要
* 次のメソッドを実装し、APIから天気取得
* 天気取得のAPIを時間がかかるタイプのAPIに変更
```swift
func fetchWeather(at area: String, date: Date) -> SignalProducer<WeatherResult, Error>
```

2022-03-15 06:09 UTC, dazy1030 commented on YumemiTraining/YumemiTraining/ReactiveWeatherViewController.swift
> +        let weatherSignalProducer = self.weatherModel.fetchWeather(at: "tokyo", date: Date())
@torakyun 
特に定義しなくても大丈夫です。そのままstartWithResultを呼んでも大丈夫です

2022-03-15 06:15 UTC, dazy1030 commented on YumemiTraining/YumemiTraining/ReactiveWeatherViewController.swift
> +                self?.handleWeather(result)
@torakyun 
ReactiveSwiftにはどのスレッドで結果を受け取るかを指定することのできるオペレータが存在します。
まずはDispatchQueue.main.asyncを外して、メインスレッド以外から実行することでUIをメインスレッド外から呼ぶと警告が出る（紫色の警告）ことを確認した上で、以下のオペレータを使用して警告が出なくなることを確認してください。
```swift
weatherSignalProducer.observe(on: UIScheduler()).startWithResult { [weak self] result in
    ...
}
```

2022-03-15 07:40 UTC, dazy1030 commented on YumemiTraining/YumemiTraining/APIs/WeatherModelImpl.swift
> +                    let weatherResult = try decoder.decode(WeatherResult.self, from: weatherResultData)
@torakyun 
通常は複数のAPIが存在しますので、共通化できる処理は共通化しておきましょう。
APIの処理の流れは、
1. パラメータを引数で受け取る
2. パラメータをバイナリ（Data）やJSON（String）にエンコードする
3. API実行
4. レスポンスをデコード
5. 結果を返す

どれも固有の処理に見えますが、2と4は共通化することができます
2は、 `Encodable` に準拠する型からエンコードできる。
```swift
func encodeToJSON<T: Encodable>(parameter: T) throws -> String {
   ...
}
```
4は、 `Decodable` に準拠する型へデコードできる。
```swift
func decodeJSON<T: Decodable>(_ json: String) throws -> T {
   ...
}
```
という書き方ができます。 
これはSwiftの記法の一つで `Generics` と言います。https://docs.swift.org/swift-book/LanguageGuide/Generics.html

難しかったらヒント出しますのでLINEどうぞ！

2022-03-15 07:41 UTC, dazy1030 requested changes
e5d6ab3637bc21f566617faf9f154c93e744c853 まで確認

2022-03-15 07:51 UTC, dazy1030 commented
@torakyun 
もしXcodeをアップデートするなら、おそらくですが `Package.resolved` というファイルに変更が加わります
今後ずっと出続ける変更なので、このPRでコミットしていただいて構いません。

2022-03-16 03:45 UTC, torakyun commented on YumemiTraining/YumemiTraining/ReactiveWeatherViewController.swift
> +        let weatherSignalProducer = self.weatherModel.fetchWeather(at: "tokyo", date: Date())
https://github.com/torakyun/yumemi_training/pull/31/commits/b5f7245cd10b7549af8a4a56c390e8785186a111
こちらで修正しました。

2022-03-16 03:46 UTC, torakyun commented on YumemiTraining/YumemiTraining/ReactiveWeatherViewController.swift
> +                self?.handleWeather(result)
https://github.com/torakyun/yumemi_training/pull/31/commits/02eee0a4a85d433bd3610808f84ea374aa270dd1
このコミットで修正しました。

2022-03-16 03:46 UTC, torakyun commented on YumemiTraining/YumemiTraining/APIs/WeatherModelImpl.swift
> +                    let weatherResult = try decoder.decode(WeatherResult.self, from: weatherResultData)
https://github.com/torakyun/yumemi_training/pull/31/commits/8ac96c6638e39d83770471681fcd5bf35c4af4e1
このコミットで修正しました。

2022-03-16 03:47 UTC, torakyun commented on YumemiTraining/YumemiTraining/APIs/WeatherModelImpl.swift
> +                    let weatherResult = try decoder.decode(WeatherResult.self, from: weatherResultData)
とりあえず自分で書いてみました！

2022-03-16 04:35 UTC, dazy1030 commented on YumemiTraining/YumemiTraining/ReactiveWeatherViewController.swift
> +                self?.handleWeather(result)
@torakyun 
終わりの中括弧の位置がおかしいので、修正お願いします。

2022-03-16 04:50 UTC, dazy1030 commented on YumemiTraining/YumemiTraining/APIs/WeatherModelImpl.swift
> +                    let weatherResult = try decoder.decode(WeatherResult.self, from: weatherResultData)
@torakyun 
おしいですね。エンコードのメソッドについてはOKです。
ジェネリクスを引数に適用する場合、メソッドを使う側で引数の型を決めます。
```swift
struct Parameter: Encodable {
   ...
}

func encode<T: Encodable>(parameter: T) throws -> String {
    ...
}

let parameter = Parameter(...)
let json = try encode(parameter: parameter)
```

ジェネリクスを戻り値に適用する場合も同様で、メソッドを使う側で戻り値の型を決めます。
```swift
struct Response: Decodable {
   ...
}

func decode<T: Decodable>(json: String) throws -> T {
    ...
}

let json = try api()
let response: Response = try decode(json: json)
```

これらを参考に、デコードのメソッドの第一引数を削除してみてください。

2022-03-16 05:29 UTC, torakyun commented on YumemiTraining/YumemiTraining/ReactiveWeatherViewController.swift
> +                self?.handleWeather(result)
https://github.com/torakyun/yumemi_training/pull/31/commits/817f3ce6116738243f46c484a7fd5e67385b9079
こちらで修正しました。

2022-03-16 05:29 UTC, torakyun commented on YumemiTraining/YumemiTraining/APIs/WeatherModelImpl.swift
> +                    let weatherResult = try decoder.decode(WeatherResult.self, from: weatherResultData)
https://github.com/torakyun/yumemi_training/pull/31/commits/5fa7bf8f50c722dccb3335a8d0745c9d65bab5c4
こちらで修正しました。

2022-03-16 06:00 UTC, dazy1030 approved these changes
5fa7bf8f50c722dccb3335a8d0745c9d65bab5c4 まで確認

2022-03-16 07:17 UTC, merged