JSON文字列を扱う
torakyun/yumemi_training pull request #9
Opened 2022-03-02 09:47 UTC by torakyun

## 概要 

[Session4. JSON文字列](https://github.com/yumemi-inc/ios-training/blob/main/Documentation/Json.md)

## 修正内容 

- JSON文字列を入出力とする天気予報APIに変更
- UILabelに最高気温と最低気温を表示

|before|after| 
|-----|-----| 
|<img width="362" alt="スクリーンショット 2022-03-02 10 48 42" src="https://user-images.githubusercontent.com/67317828/156336548-a886f9fa-2999-4da0-8cdd-6cf741a8d541.png">|<img width="359" alt="スクリーンショット 2022-03-02 18 46 50" src="https://user-images.githubusercontent.com/67317828/156337093-d7ee8b14-238a-4b70-8831-7a3d58879a03.png">|

2022-03-03 03:17 UTC, dazy1030 requested changes
1fefb1762f548ead1635d652aed885b7304f3c01 まで確認

2022-03-03 03:17 UTC, dazy1030 commented on YumemiTraining/YumemiTraining/ViewController.swift
> +            let jsonStr = String(bytes: jsonData, encoding: .utf8)!
@torakyun 
基本的に、force unwrap（Optional型に!をつけるやつ）やforce cast（as! でキャストするやつ）はやめましょう。
以下を参考に、このメソッドのもの全てに修正をお願いします。

* Optionalを安全に外すには `if let` または `guard let` を使用しますが、今回のようにOptionalが外せなきゃ次の処理が全部できない、みたいな場合には `guard let` を使用します。
```swift
❎
let string = String(data: data, encoding: .utf8)!
⭕️
guard let string = String(data: data, encoding: .utf8) else { return }
```

* ただし、guard 文を使用するとその時点で処理を終えなければなりません。戻り値のない関数であれば `return` で問題ありません。
```swift
func sample() {
    ...
    guard let string = String(data: data, encoding: .utf8) else { return }
    ...
}
```

* 戻り値がある場合は、エラー処理または戻り値をOptionalにするのが普通です。
```swift
// Before
func sample() -> String {
    ...
   let string = String(data: data, encoding: .utf8)!
    ...
}
// After
// このエラーの書き方でなくとも、エラーが定義できれば大丈夫です。
enum SampleError: Error {
    case decodeDataFailed
}
func sample() throws -> String {
    ...
   guard let string = String(data: data, encoding: .utf8) else {
        throw SampleError.decodeDataFailed
    }
    ...
}
// or
func sample() -> String? {
    ...
    guard let string = String(data: data, encoding: .utf8) else { return nil }
    ...
}
```

* force castについても同じ考え方です。
```swift
guard let int = dict["temp"] as? Int else { return }
```

2022-03-03 03:17 UTC, dazy1030 commented on YumemiTraining/YumemiTraining/ViewController.swift
> +            let jsonStr = String(bytes: jsonData, encoding: .utf8)!
@torakyun 
DataからStringを作る時、`String(bytes:encoding:)` はあまり使用しませんね。
`String(data:encoding:)` の方を使用してみてください。

2022-03-04 01:46 UTC, torakyun commented on YumemiTraining/YumemiTraining/ViewController.swift
> +            jsonObj["date"] = "2020-04-01T12:00:00+09:00"
https://github.com/torakyun/yumemi_training/pull/9/commits/05a01f891b504bc098109c836be959001b0cbd31
このコミットで修正しました。

2022-03-04 01:47 UTC, torakyun commented on YumemiTraining/YumemiTraining/ViewController.swift
> +            let jsonStr = String(bytes: jsonData, encoding: .utf8)!
https://github.com/torakyun/yumemi_training/pull/9/commits/46b34b3459847af14da11442492155614528573b
このコミットで修正しました。

2022-03-04 01:47 UTC, torakyun commented on YumemiTraining/YumemiTraining/ViewController.swift
> +            let jsonStr = String(bytes: jsonData, encoding: .utf8)!
https://github.com/torakyun/yumemi_training/pull/9/commits/76b35e266d2bb832e36beea267cf52a61075ce20
このコミットで修正しました。

2022-03-04 01:48 UTC, torakyun commented on YumemiTraining/YumemiTraining/ViewController.swift
> +            var jsonObj = Dictionary<String, Any>()
次のコメントと同時に修正しました。

2022-03-04 02:02 UTC, dazy1030 requested changes
76b35e266d2bb832e36beea267cf52a61075ce20 まで確認

2022-03-04 02:02 UTC, dazy1030 commented on YumemiTraining/YumemiTraining/ViewController.swift
> +            guard let weatherData: Data =  weatherJsonStr.data(using: String.Encoding.utf8) else {
@torakyun 
すいません、前回指摘し忘れましたが不要な型の記載は行わなくて良いです。あとスペースが一つ多いようですね。
```suggestion
            guard let weatherData = weatherJsonStr.data(using: String.Encoding.utf8) else {
```

2022-03-04 02:51 UTC, torakyun commented on YumemiTraining/YumemiTraining/ViewController.swift
> +            }
https://github.com/torakyun/yumemi_training/pull/9/commits/6e30bb837fd19669a79ec14daa9692891bf5d9a8
このコミットで修正しました。

2022-03-04 02:51 UTC, torakyun commented on YumemiTraining/YumemiTraining/ViewController.swift
> +            guard let weatherData: Data =  weatherJsonStr.data(using: String.Encoding.utf8) else {
https://github.com/torakyun/yumemi_training/pull/9/commits/5e48543c8ed8497a2929d173df73401cc97ebbd5
このコミットで修正しました。

2022-03-04 03:00 UTC, dazy1030 approved these changes
5e48543c8ed8497a2929d173df73401cc97ebbd5
LGTM!

2022-03-04 03:01 UTC, merged